### ISSUE TITLE
[Bug] Book not opening

### ISSUE THREAD

**Issue by mystic-man-rhino** [Anxcye/anx-reader#655]
I tried this book in other readers (libreara,moon+,) across platform it works, but in only 'anx reader' it doesn't work. It's not giving any error but trying to open just goes blank.

link to the book:
https://limewire.com/d/mTKhd#9IcIjEef62

**Comment by Anxcye** [comment]
Can you provide a log file after the problem occurs? 

https://github.com/Anxcye/anx-reader/blob/develop/docs/troubleshooting.md#how-to-obtain-log-files

**Comment by mystic-man-rhino** [comment]
Log: 

INFO^*^ 2025-12-21 18:53:38.820151^*^ [Failed to refresh book list: Bad state: Cannot use "ref" after the widget was disposed.],null

**Comment by mystic-man-rhino** [comment]
File:

https://limewire.com/d/Fhgm1#tJivpDBqqA

Tried uploading here, but it gives error.

**Comment by Anxcye** [comment]
Can you provide the full log file? Click on the top right corner to export this file

**Comment by mystic-man-rhino** [comment]
![AnxReader-Log-2025-12-21.txt](https://github.com/user-attachments/files/24278975/AnxReader-Log-2025-12-21.txt)

**Comment by Anxcye** [comment]
This issue may have been solved, you can try the latest version

**Comment by mystic-man-rhino** [comment]
I Updated to 1.11.0 tried opening same book but issue persists. 

Attaching log file.![AnxReader-Log-2026-1-30.txt](https://github.com/user-attachments/files/24954640/AnxReader-Log-2026-1-30.txt)
